# 开发环境配置
server:
  #  配置后端端口号
  port: 9999


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parking?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    port: 6379
    host: localhost
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


logging:
  level:
    com.laoayu.parking: debug

#处理逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
#扫描所有entity包
  type-aliases-package: com.laoayu.parking.*.entity
